# version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16-trixie
    container_name: postgres_lab
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: labdb
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    # Custom configs:
        - ./postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
        - ./postgres-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command:
      [
        "postgres",
        "-c", "config_file=/etc/postgresql/postgresql.conf",
        "-c", "hba_file=/etc/postgresql/pg_hba.conf"
      ]

  mongodb:
    image: mongo:8.0
    container_name: mongo_lab
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cassandra:
    image: cassandra:5.0
    container_name: cassandra_lab
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  postgres_data:
  mongo_data:
  cassandra_data:
